name: CustomDrop
version: 1.0.0
api: 4.0.0
author: refaltor
main: refaltor\CustomDrop\CustomDrop
website: https://discord.gg/pgVSyWXgVK
description: Lets you add drops with chances, infinitely configurable!
